### ISSUE TITLE
Empty map can't be streamed?

### ISSUE THREAD

**Issue by caprica** [jacob-ebey/turbo-stream#26]
I am using Remix.run which I understand uses v2.0.0 of this library for sending responses between server and client.  I am not sure if this an issue for Remix, or if it belongs here.

I have an object that contains two maps, either of them could be empty. 

When I log the object prior to serialisation it looks like this:

```
features: {
    activated: Map(0) {},
    notActivated: Map(2) {
      'someCoolFeature' => false,
      'anotherCoolFeature' => false,
    }
  }
```

Remix reports this and the page fails to render:

> Unable to decode turbo-stream response from [whatever url]

If I return null instead of empty map:

```
features: {
    activated: null,
    notActivated: Map(2) {
      'someCoolFeature' => false,
      'anotherCoolFeature' => false,
    }
  }
```

This has no error and the page renders correctly, although I would rather deal with an empty map instead of a null.

So the question is should empty maps be serialisable?

**Comment by jacob-ebey** [comment]
Fixed by https://github.com/jacob-ebey/turbo-stream/pull/27

**Comment by jacob-ebey** [comment]
Closing for now. Please re-open if the issue persists.
