### ISSUE TITLE
Promises resolving the same value are handled incorrectly

### ISSUE THREAD

**Issue by linkvt** [jacob-ebey/turbo-stream#28]
Hi,

it seems that I found a bug with turbo-stream handling promises resolving the same vlaue incorrectly.

I originally opened https://github.com/remix-run/remix/issues/9466 but decided to dig a bit deeper and found the problem in this package.
In short, instead of the value of the second promise (resolving the same value) an empty array is returned like this:
```
[...{"31":32,"33":34,"35":36},"promiseA",["P",32],"somethingStatic",0,"promiseB",["P",36]]
P32:[1]
P36:[]
```

### Analysis

It seems to me, that flatten is used to flatten the initial array but also responses of resolved promises:
https://github.com/jacob-ebey/turbo-stream/blob/a72f7a76e393cf43b265036521d519c22f2c3c08/src/turbo-stream.ts#L171

The problem is, that on resolving the 2nd promise this check here does not add a new value to the response, as it was already returned with the first promise:
https://github.com/jacob-ebey/turbo-stream/blob/a72f7a76e393cf43b265036521d519c22f2c3c08/src/flatten.ts#L24-L25

The consequence is, that an empty array is returned here:
https://github.com/jacob-ebey/turbo-stream/blob/a72f7a76e393cf43b265036521d519c22f2c3c08/src/turbo-stream.ts#L177-L184

This causes an error in the `unflatten` function which checks for an empty erray:
https://github.com/jacob-ebey/turbo-stream/blob/a72f7a76e393cf43b265036521d519c22f2c3c08/src/unflatten.ts#L35

### Possible Fix

After looking through the code it seems to me, that we cannot reference previous values when unflattening the value of a promise.
Because of this my quick fix was to send the whole promise again, which is of course not optimal.

I opened a PR with a test case and a fix, see #29 

Best, Vincent

**Comment by jacob-ebey** [comment]
Closing for now. Please re-open if the issue persists. Thanks for the detailed report.
