### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by lilouartz** [jacob-ebey/turbo-stream#33]
I have a fairly complex JSON object structure that the server returns. You can see an example here:

https://pillser.com/probiotics/bifidobacterium-animalis

At the moment it is failing with:

```
Uncaught RangeError: Maximum call stack size exceeded
    at Object.er (turbo-stream.mjs:173:10)
    at Object.Qi (turbo-stream.mjs:322:22)
    at async Xi (turbo-stream.mjs:292:19)
```

It happened after I added additional nested json. Still figuring out how to fix it.

**Comment by lilouartz** [comment]
This is Remix response, if helpful https://gist.github.com/lilouartz/37408a26830d5b66da8d4dfb5988485f

**Comment by jacob-ebey** [comment]
Are you returning DB queries or something directly? That is a MASSIVE payload. I'll look into this when I have time, but for now, if I were you, I'd try my best to cut down the amount of data you are returning from your loaders by pre-processing the return. Your response is 4MB as is!

**Comment by carinakoo8** [comment]
I have run into this error as well with a large payload. The json structure of the data is relatively flat, something like
```
{ data: [
  { c0_column_name: 'web confirmation WR1767900' },
  { c0_column_name: 'web confirmation WR1767897' },
  { c0_column_name: 'web confirmation WR1767893' },
  { c0_column_name: 'web confirmation WR1767890' },
  { c0_column_name: 'web confirmation WR1767881' },
  { c0_column_name: 'web confirmation WR1767866' }
]}
```
It works after I cut the payload to about 2.5 MB. It would be great to have guidance on whether this can be expected to work with larger payloads!

**Comment by jacob-ebey** [comment]
Should be fixed in https://github.com/jacob-ebey/turbo-stream/releases/tag/v2.2.2
